### ISSUE TITLE
docker-mautic no longer maintained?

### ISSUE THREAD

**Issue by GuidoDr** [mautic/docker-mautic#183]
Is docker-mautic no longer maintained?

version 2 is still on 2.16.2 eventhough 2.16.4 of mautic is the current version
version 3 is still on 3.0.2 eventhough 3.2.1 of mautic is the current version

I would like to upgrade my docker-compose installation from version 2 to 3 but that is not possible since the current v2 image is only 2.16.2 which does include an outdated php version which is not compatible with the upgrade script to v3. Therefore the upgrade from the console is not possible.

**Comment by EnziinSystem** [comment]
I believe the trend of the future is that people will run Mautic in container-orchestration like Kubernetes, so I expect the project to upgrade to 3.x soon and maintenance.

**Comment by alderson59** [comment]
I had this issue https://github.com/mautic/docker-mautic/issues/182

And even though I now manage to get it running on v3, I am trying to update it to v3.2.2 (via web interface) - and doing so causes a bunch of errors for me. Campaign builder doesn't work, segments don't work.

Not a dev, so editing code manually a lot to keep it updated is quite time consuming and messy to say the least.

Hoping that the docker hub repository updates this image to the latest v3.2 so that it can be installed seamlessly.

Otherwise, thanks all for this amazing project. Rooting for it!

**Comment by user592965** [comment]
The image on docker hub is 6 month old, I was also asking myself if it was abandoned.

**Comment by paolomainardi** [comment]
The repo is maintained and very well updated: https://github.com/mautic/docker-mautic/tree/mautic3

**Comment by GuidoDr** [comment]
well, sorry to say, but it does not help if the v3 is now maintained again (was also not maintained for several months until this week) since the v2 is still using an outdated php version which prevents an upgrade to v3.

**Comment by mathewmeconry** [comment]
I just asked my self the same question and it is good that we see progress on different branches in this repo. 
BUT as long as the docker images are only built and not pushed this doesn't help anybody....
the latest image on dockerhub is again over 4 months old and no releases on github packages.

**Comment by wget** [comment]
Hey there :wave: William from Collabora =) As we are using Mautic for internal purpose in a brand new Docker infra, we are now committing to upstream all our changes and thus maintain this repo. Thanks for the patience as we are just starting to make this happen =)

Closing. =)
