### ISSUE TITLE
Regression 4.0.2? Redirection loop to same URL

### ISSUE THREAD

**Issue by rvalle** [mautic/docker-mautic#220]
### Mautic Version

4.0.0

### PHP version

php@mautic-docker

### What browsers are you seeing the problem on?

Firefox

### What happened?

4.0.1 is working fine behind haproxy with SSL termination.
after updating to 4.0.2 a redirect loop is introduced.
the redirect loop is peculiar because it loops to the exact same URL:  ```site_url```

### How can we reproduce this issue?

Step 1:  install mautic 4.01 behind haproxy,
Step 2: browse to https://site_url, all working
Step 2: update to 4.0.2 with console mautic:update:apply
Step 3: browse to your https://site_url : browser warns of invalid redirection
Step 4: wget https://site_url verify which redireciton is taking place https://site_url is moved permanently 301 to https://site_url

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by wget** [comment]
I cannot explicitly reproduce, but I'm clearing and resetting the permissions after each upgrade, explaining maybe why it is working for my side and not yours =)

A few tracks to fix this issue:

1. Clear the cache and fix permissions:
```
root@a151cba214a7:/var/www/html# rm -r app/cache/
root@a151cba214a7:/var/www/html# php bin/console cache:clear --env=prod
root@a151cba214a7:/var/www/html# chown -R www-data:www-data .
```

2. Ensure the cache related settings in `app/config/local.php` are correct and haven't been overwritten during the update.

Feel free to reopen or post your problem to [the forum](https://forum.mautic.org/) as this problem is not likely due to this Dockerfile =)
